#exception handling
#try - find errors

'''try:
    print(x)
except NameError:
    print("variable x is not defined")
except:
    print("an exception occured")


try:
    print("Hello")
except:
    print("an exception occured")
else:
    print("Nothing went wrong")'''
    


'''try:
    print(x)
except:
    print("an exception occured")
finally:
    print("TryExcept is finished")
'''